# Generated by Django 4.1.2 on 2022-11-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='dwsc',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='services',
            name='phone',
        ),
    ]
