# Generated by Django 4.1.2 on 2022-11-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_dwsc_services_desc_remove_services_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='fname',
            new_name='name',
        ),
    ]
