# Generated by Django 4.1.2 on 2022-11-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_fname_services_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='servicemodule',
        ),
    ]
